import Image from "next/image";
import avatarluk from "../public/avatar-removebg.png";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillGithub,
  AiFillLinkedin,
} from "react-icons/ai";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  return (
    <div>
      <head>
        <title>Luk Imperinetti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-medium">Luk IMPERINETTI</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-purple-900 to-blue-800 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Mon CV
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-transparent bg-clip-text bg-gradient-to-r from-purple-900 to-blue-800 font-medium md:text-6xl">
              Développeur FullStack
            </h2>
            <p className="text-2cl py-2 leading-8 text-gray-600 md:text-3xl">
              Texte a modifier plus tard
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            {/* <AiFillTwitterCircle className="cursor-pointer" /> */}
            <AiFillGithub className="cursor-pointer" />
            <AiFillLinkedin className="cursor-pointer" />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-purple-900 to-blue-800 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-85 md:w-85">
            <Image
              src={avatarluk}
              alt="dev-ed"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>

        {/* body section */}

        <section>
          <div>
            <h3 className="text-3xl py-10 text-transparent bg-clip-text bg-gradient-to-r from-purple-900 to-blue-800 font-medium">
              A propos de moi
            </h3>
            <p className="text-2cl py-2 leading-8 text-gray-600">
              Texte a <spans className="text-teal-500">changer</spans> plus tard
              aussi
            </p>
            <p className="text-gray-600">
              Texte a <spans className="text-teal-500">changer</spans> plus tard
              aussi
            </p>
            <p className="text-gray-600">
              Texte a <spans className="text-teal-500">changer</spans> plus tard
              aussi
            </p>
          </div>
          {/* Afficher mon parcours d'apprentissage step by step : Autodidacte, Wac, MSC */}
          <h3 className="text-3xl py-10 text-transparent bg-clip-text bg-gradient-to-r from-purple-900 to-blue-800 font-medium">
            Expériences Pro
          </h3>
          <div className="lg:flex gap-5 justify-center">
            <div className="text-center shadow-lg p-10 rounder-xl my-10">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h4 className="text-lg font-medium pt-8 pb-2">Autodidacte</h4>
              <p>
                Texte qui decrit mon porjet. il était vraiment bien de fou !
              </p>
              <h5>Techno utilisé : </h5>
              <p className="text-gray-800 py-1">ca</p>
              <p>ca</p>
              <p>et ca</p>
            </div>

            <div className="text-center shadow-lg p-10 rounder-xl my-10">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h4 className="text-lg font-medium pt-8 pb-2">WebAcadémie</h4>
              <p>
                Texte qui decrit mon porjet. il était vraiment bien de fou !
              </p>
              <h5>Techno utilisé : </h5>
              <p className="text-gray-800 py-1">ca</p>
              <p>ca</p>
              <p>et ca</p>
            </div>
          </div>
          <div>
            <h3 className="text-3xl py-10 text-transparent bg-clip-text bg-gradient-to-r from-purple-900 to-blue-800 font-medium">
              Fortmations
            </h3>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <ol className="relative border-l border-gray-200 dark:border-gray-700">
                <li className="mb-10 ml-4">
                  <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                  <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
                    February 2022
                  </time>
                  <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
                    Application UI code in Tailwind CSS
                  </h3>
                  <p class="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">
                    Get access to over 20+ pages including a dashboard layout,
                    charts, kanban board, calendar, and pre-order E-commerce &
                    Marketing pages.
                  </p>
                  <a
                    href="#"
                    class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:outline-none focus:ring-gray-200 focus:text-blue-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-gray-700"
                  >
                    Learn more{" "}
                    <svg
                      class="w-3 h-3 ml-2"
                      aria-hidden="true"
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 14 10"
                    >
                      <path
                        stroke="currentColor"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M1 5h12m0 0L9 1m4 4L9 9"
                      />
                    </svg>
                  </a>
                </li>
                <li className="mb-10 ml-4">
                  <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                  <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
                    March 2022
                  </time>
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                    Marketing UI design in Figma
                  </h3>
                  <p className="text-base font-normal text-gray-500 dark:text-gray-400">
                    All of the pages and components are first designed in Figma
                    and we keep a parity between the two versions even as we
                    update the project.
                  </p>
                </li>
                <li className="ml-4">
                  <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-900 dark:bg-gray-700"></div>
                  <time className="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">
                    April 2022
                  </time>
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                    E-Commerce UI code in Tailwind CSS
                  </h3>
                  <p className="text-base font-normal text-gray-500 dark:text-gray-400">
                    Get started with dozens of web components and interactive
                    elements built on top of Tailwind CSS.
                  </p>
                </li>
              </ol>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-10 text-transparent bg-clip-text bg-gradient-to-r from-purple-900 to-blue-800 font-medium">
              Portfolio
            </h3>
            <p className="text-2cl py-2 leading-8 text-gray-600">
              Voici mes différents{" "}
              <spans className="text-teal-500">projets</spans> réalisés pour
              l'école et en autodidacte
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
