import Image from "next/image";
import avatarluk from "../public/avatar-removebg.png";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillGithub,
  AiFillLinkedin,
} from "react-icons/ai";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  return (
    <div>
      <head>
        <title>Luk Imperinetti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-medium">Luk IMPERINETTI</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-purple-900 to-blue-800 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Mon CV
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-transparent bg-clip-text bg-gradient-to-r from-purple-900 to-blue-800 font-medium md:text-6xl">
              Développeur FullStack
            </h2>
            <p className="text-2cl py-2 leading-8 text-gray-600 md:text-3xl">
              Texte a modifier plus tard
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            {/* <AiFillTwitterCircle className="cursor-pointer" /> */}
            <AiFillGithub className="cursor-pointer" />
            <AiFillLinkedin className="cursor-pointer" />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-purple-900 to-blue-800 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image
              src={avatarluk}
              alt="dev-ed"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>

        {/* body section */}

        <section>
          <div>
            <h3 className="text-3xl py-10 text-transparent bg-clip-text bg-gradient-to-r from-purple-900 to-blue-800 font-medium">
              A propos de moi
            </h3>
            <p className="text-2cl py-2 leading-8 text-gray-600">
              Texte a <spans className="text-teal-500">changer</spans> plus tard
              aussi
            </p>
            <p className="text-gray-600">
              Texte a <spans className="text-teal-500">changer</spans> plus tard
              aussi
            </p>
            <p className="text-gray-600">
              Texte a <spans className="text-teal-500">changer</spans> plus tard
              aussi
            </p>
          </div>
          {/* Afficher mon parcours d'apprentissage step by step : Autodidacte, Wac, MSC */}
          <div className="lg:flex gap-5">
            <div className="text-center shadow-lg p-10 rounder-xl my-10">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h4 className="text-lg font-medium pt-8 pb-2">Autodidacte</h4>
              <p>
                Texte qui decrit mon porjet. il était vraiment bien de fou !
              </p>
              <h5>Techno utilisé : </h5>
              <p className="text-gray-800 py-1">ca</p>
              <p>ca</p>
              <p>et ca</p>
            </div>

            <div className="text-center shadow-lg p-10 rounder-xl my-10">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h4 className="text-lg font-medium pt-8 pb-2">WebAcadémie</h4>
              <p>
                Texte qui decrit mon porjet. il était vraiment bien de fou !
              </p>
              <h5>Techno utilisé : </h5>
              <p className="text-gray-800 py-1">ca</p>
              <p>ca</p>
              <p>et ca</p>
            </div>

            <div className="text-center shadow-lg p-10 rounder-xl my-10">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h4 className="text-lg font-medium pt-8 pb-2">MSc-pro</h4>
              <p>
                Texte qui decrit mon porjet. il était vraiment bien de fou !
              </p>
              <h5>Techno utilisé : </h5>
              <p className="text-gray-800 py-1">ca</p>
              <p>ca</p>
              <p>et ca</p>
            </div>
          </div>
          <div>
            <h3 className="text-3xl py-10 text-transparent bg-clip-text bg-gradient-to-r from-purple-900 to-blue-800 font-medium">
              Expérience Pro
            </h3>
            <p className="text-2cl py-2 leading-8 text-gray-600">
              Texte a <spans className="text-teal-500">changer</spans> plus tard
              aussi
            </p>
            <p className="text-gray-600">
              Texte a <spans className="text-teal-500">changer</spans> plus tard
              aussi
            </p>
            <p className="text-gray-600">
              Texte a <spans className="text-teal-500">changer</spans> plus tard
              aussi
            </p>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-10 text-transparent bg-clip-text bg-gradient-to-r from-purple-900 to-blue-800 font-medium">
              Portfolio
            </h3>
            <p className="text-2cl py-2 leading-8 text-gray-600">
              Voici mes différents{" "}
              <spans className="text-teal-500">projets</spans> réalisés pour
              l'école et en autodidacte
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
